### ISSUE TITLE
ImageReader bug with non-square images?

### ISSUE THREAD

**Issue by dmagee** [Microsoft/CNTK#492] opened 2016-05-19 13:08 UTC
I'm loading some non-square images with ImageReader (2048x1024) and it is loading wrong. The tensor created is the correct size, but consists of the middle 1024 pixels (horizontally) of the file on disk stretched out to 2048 pixels in width - rather than the original 2048 pixel image. I think I have everything right in the .cnkt and .ndl:

.cntk (all sections):

```
reader = [
    readerType = "ImageReader"
    file =images.txt
    randomize=None
    features=[
        width=2048
        height=1024
        channels=3
    ]
    labels=[
        labelDim=3
    ]
]
```

.ndl ...

   ImageW = 2048
    ImageH = 1024
    ImageC = 3
    LabelDim = 3   

```
features = ImageInput(ImageW, ImageH, ImageC, tag = feature, imageLayout = "cudnn")
```

I've checked and the files on disk are definitely 2048x1024

Derek

P.S. It works fine with 1024x1024 square images

**Comment by cha-zhang** [comment] 2017-07-29 00:50
CNTK should be able to read non-square images. Please try the latest CNTK 2.0 and see if the problem still exists. 

I'll close this for now. Feel free to open a new issue if the problem is not resolved. Thanks!

**Closed by cha-zhang** 2017-07-29 00:50 UTC
