### ISSUE TITLE
CUDA failure 77: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#1850] opened 2017-05-07 09:53 UTC
```
CUDA failure 77: an illegal memory access was encountered ; GPU=0 ; hostname=************** ; expr=cudaMemcpy(pArray, Data(), sizeof(ElemType) * m_numRows * m_numCols, cudaMemcpyDeviceToHost)
```
Why are CUDA exceptions resulting in CNTK/dump crash? There is no error handling to re-attempt memcpy or other cuda primitives?

[http://stackoverflow.com/questions/14038589/what-is-the-canonical-way-to-check-for-errors-using-the-cuda-runtime-api](http://stackoverflow.com/questions/14038589/what-is-the-canonical-way-to-check-for-errors-using-the-cuda-runtime-api)

Of note is this github project (GNU Lesser General Public License v3.0):  [cuda-api-wrappers C++/cuda 8+](https://github.com/eyalroz/cuda-api-wrappers)

PS: the other suggestion would be to skip that MB evaluation (the one that triggered error) and move on. skipping few MB would not matter (say up to a critical error count), while restarting entire computation/farm has impact.

**Comment by mahilleb-msft** [comment] 2017-07-17 16:22
Most of the time, due to the asynchronous nature of launching/completing CUDA kernels, the problem is not with the call (here: memcpy), but with earlier kernel launches. Normally, it's also a code / library bug, that should be fixed; and retrying would be bad for perf.
Could you share a repro, and what environment you're in?

**Comment by mahilleb-msft** [comment] 2017-07-25 13:37
Closing for now... please re-open if you have a repro / more info on this specific repro... Thanks!

**Closed by mahilleb-msft** 2017-07-25 13:37 UTC
Labels: need more info

**Comment by vermorel** [comment] 2017-08-14 16:42
I am also getting those errors, mostly on super-large datasets (multi GB of binary data) which makes the problem hard to reproduce. However, it seems to happen in a rather deterministic fashion for some datasets.
