### ISSUE TITLE
Procedure not found in CPPEvalClient.cpp

### ISSUE THREAD

**Issue by StephieX** [Microsoft/CNTK#1199] opened 2016-12-23 20:15 UTC
Sorry, I found the answer to this.  I had a stray dll on a search path that apparently was being loaded.  I would delete the thread if I could.

Hello, I'm trying to run an example, CPPEvalCleint.cpp, with the prebuilt binaries CNTK-2-0-beta7-0-Windows-64bit-GPU-1bit-SGD.zip.

1st issue was that the Debug version doesn't work.  It fails on model->CreateNetwork(networkConfiguration);  That's OK because I can use the release version to get past that error.  

However,   model->Evaluate(inputLayer, outputLayer); fails claiming that a procedure isn't found.  

I'm thinking that both these issues have something to do with a dll being loaded at runtime that doesn't quite match the rest of the binaries, but who knows.

I'm using the AN4 example model instead of the one that was originally pointed to in the source.  I can't see where that would make a difference from the code, but I could be wrong.

int main(int argc, char* argv[])
{
    // Get the binary path (current working directory)
    argc = 0;   
    std::string app = argv[0];
    std::string path; 
    IEvaluateModel<float> *model;
    size_t pos;
    int ret;

#ifdef _WIN32
    pos = app.rfind("\\");
    path = (pos == std::string::npos) ? "." : app.substr(0, pos);

    // This relative path assumes launching from CNTK's binary folder, e.g. x64\Release
    std::string modelWorkingDirectory = path + "/../../Examples/Image/GettingStarted";

	modelWorkingDirectory = "D:/apis/cntk/Examples/Speech/AN4";
#else // on Linux
    pos = app.rfind("/");
    path = (pos == std::string::npos) ? "." : app.substr(0, pos);

    // This relative path assumes launching from CNTK's binary folder, e.g. build/cpu/release/bin/
    const std::string modelWorkingDirectory = path + "/../../../../Examples/Image/GettingStarted";
#endif
    std::string modelFilePath = modelWorkingDirectory + "/Output/Models/01_OneHidden";

	modelFilePath = modelWorkingDirectory + "/Output/Models/cntkSpeechFF.dnn";

    try
    {
        struct stat statBuf;
        if (stat(modelFilePath.c_str(), &statBuf) != 0)
        {
            fprintf(stderr, "Error: The model %s does not exist. Please follow instructions in README.md in <CNTK>/Examples/Image/GettingStarted to create the model.\n", modelFilePath.c_str());
            return(1);
        }

        GetEvalF(&model);

        // Load model with desired outputs
        std::string networkConfiguration;
        // Uncomment the following line to re-define the outputs (include h1.z AND the output ol.z)
        // When specifying outputNodeNames in the configuration, it will REPLACE the list of output nodes 
        // with the ones specified.
        //networkConfiguration += "outputNodeNames=\"h1.z:ol.z\"\n";
        networkConfiguration += "modelPath=\"" + modelFilePath + "\"";
		networkConfiguration += "modelPath=" + modelFilePath;
		model->CreateNetwork(networkConfiguration);

        // get the model's layers dimensions
        std::map<std::wstring, size_t> inDims;
        std::map<std::wstring, size_t> outDims;
        model->GetNodeDimensions(inDims, NodeGroup::nodeInput);
        model->GetNodeDimensions(outDims, NodeGroup::nodeOutput);

        // Generate dummy input values in the appropriate structure and size
        auto inputLayerName = inDims.begin()->first;
        std::vector<float> inputs;
        for (int i = 0; i < inDims[inputLayerName]; i++)
        {
            inputs.push_back(static_cast<float>(i % 255));
        }

        // Allocate the output values layer
        std::vector<float> outputs;

        // Setup the maps for inputs and output
        Layer inputLayer;
        inputLayer.insert(MapEntry(inputLayerName, &inputs));
        Layer outputLayer;
        auto outputLayerName = outDims.begin()->first;
        outputLayer.insert(MapEntry(outputLayerName, &outputs));

        // We can call the evaluate method and get back the results (single layer)...
        model->Evaluate(inputLayer, outputLayer);

        // Output the results
        fprintf(stderr, "Layer '%ls' output:\n", outputLayerName.c_str());
        for (auto& value : outputs)
        {
            fprintf(stderr, "%f\n", value);
        }

        // This pattern is used by End2EndTests to check whether the program runs to complete.
        fprintf(stderr, "Evaluation complete.\n");
        ret = 0;
    }
    catch (const std::exception& err)
    {
        fprintf(stderr, "Evaluation failed. EXCEPTION occurred: %s\n", err.what());
        ret = 1;
    }
    catch (...)
    {
        fprintf(stderr, "Evaluation failed. Unknown ERROR occurred.\n");
        ret = 1;
    }

    fflush(stderr);
    return ret;
}

**Comment by zhouwangzw** [comment] 2016-12-25 22:18
Glad to know that you found the cause. I am closing this issue. Please reopen it at anytime when needed.

**Closed by zhouwangzw** 2016-12-25 22:18 UTC
