### ISSUE TITLE
CSEvalClient project  occur  "SelectDevice" exception

### ISSUE THREAD

**Issue by klmsj** [Microsoft/CNTK#376] opened 2016-04-20 12:05 UTC
Hi all:
I run CSEvalClient project, in the "EvaluateModelSingleLayer" method, change "deviceId=-1" to "deviceId=0" in, the rest of the 3 methods will occur  "SelectDevice" exception, may I ask how this is going on？ thank you!

PS:I trained model by GPU(set deviceId=0,in the configFile  "01_OneHidden.cntk"  )
the console output:
====== EvaluateModelSingleLayer ========
LockDevice: Locked GPU 0 to test availability.
LockDevice: Unlocked GPU 0 after testing.
LockDevice: Locked GPU 0 for exclusive use.

Post-processing network...

4 roots:
        ce = CrossEntropyWithSoftmax()
        err = ErrorPrediction()
        errTop5 = ErrorPrediction()
        ol.z = Plus()

Validating network. 17 nodes to process in pass 1.

Validating --> labels = InputValue() :  -> [10 x *]
Validating --> ol.W = LearnableParameter() :  -> [10 x 200]
Validating --> h1.W = LearnableParameter() :  -> [200 x 784]
Validating --> featScale = LearnableParameter() :  -> [1 x 1]
Validating --> features = InputValue() :  -> [784 x *]
Validating --> featScaled = ElementTimes (featScale, features) : [1 x 1], [784 x
 *] -> [784 x 1 x *]
Validating --> h1.t = Times (h1.W, featScaled) : [200 x 784], [784 x 1 x *] -> [
200 x 1 x *]
Validating --> h1.b = LearnableParameter() :  -> [200 x 1]
Validating --> h1.z = Plus (h1.t, h1.b) : [200 x 1 x *], [200 x 1] -> [200 x 1 x
 *]
Validating --> h1.y = Sigmoid (h1.z) : [200 x 1 x *] -> [200 x 1 x *]
Validating --> ol.t = Times (ol.W, h1.y) : [10 x 200], [200 x 1 x *] -> [10 x 1
x *]
Validating --> ol.b = LearnableParameter() :  -> [10 x 1]
Validating --> ol.z = Plus (ol.t, ol.b) : [10 x 1 x *], [10 x 1] -> [10 x 1 x *]

Validating --> ce = CrossEntropyWithSoftmax (labels, ol.z) : [10 x *], [10 x 1 x
 *] -> [1]
Validating --> err = ErrorPrediction (labels, ol.z) : [10 x *], [10 x 1 x *] ->
[1]
Validating --> unnamed81 = LearnableParameter() :  -> [1 x 1]
Validating --> errTop5 = ErrorPrediction (labels, ol.z, unnamed81) : [10 x *], [
10 x 1 x *], [1 x 1] -> [1]

Validating network. 9 nodes to process in pass 2.

Validating network, final pass.

9 out of 17 nodes do not share the minibatch layout with the input data.

Post-processing network complete.

Allocating matrices for forward and/or backward propagation.
Output layer: ol.z
-0.06344432
-5.483581
0.5124335
4.071426
-2.692556
4.738898
-2.843953
-5.916711
8.018162
0.315891

====== EvaluateModelMultipleLayers ========

About to throw exception 'SelectDevice: Attempted to change device selection fro
m -4 to -1 (-4 means 'auto').'
Error: SelectDevice: Attempted to change device selection from -4 to -1 (-4 mean
s 'auto').
Native CallStack:
[CALL STACK]
    > Microsoft::MSR::CNTK::  SelectDevice
    - Microsoft::MSR::CNTK::  DeviceFromConfig
    - GetModelFromConfig<Microsoft::MSR::CNTK::ConfigParameters,float>
    - Microsoft::MSR::CNTK::CNTKEval<float>::  CreateNetwork
    - 000007FE8F2D7D7E (SymFromAddr() error: 鎵句笉鍒版寚瀹氱殑妯″潡銆?

 Inner Exception: No Inner Exception

====== EvaluateNetworkSingleLayer ========

About to throw exception 'SelectDevice: Attempted to change device selection fro
m -4 to -1 (-4 means 'auto').'
Error: SelectDevice: Attempted to change device selection from -4 to -1 (-4 mean
s 'auto').
Native CallStack:
[CALL STACK]
    > Microsoft::MSR::CNTK::  SelectDevice
    - Microsoft::MSR::CNTK::  DeviceFromConfig
    - GetModelFromConfig<Microsoft::MSR::CNTK::ConfigParameters,float>
    - Microsoft::MSR::CNTK::CNTKEval<float>::  CreateNetwork
    - 000007FE8F2D7D7E (SymFromAddr() error: 鎵句笉鍒版寚瀹氱殑妯″潡銆?

 Inner Exception: No Inner Exception

====== EvaluateNetworkSingleLayerNoInput ========

About to throw exception 'SelectDevice: Attempted to change device selection fro
m -4 to -1 (-4 means 'auto').'
Error: SelectDevice: Attempted to change device selection from -4 to -1 (-4 mean
s 'auto').
Native CallStack:
[CALL STACK]
    > Microsoft::MSR::CNTK::  SelectDevice
    - Microsoft::MSR::CNTK::  DeviceFromConfig
    - GetModelFromConfig<Microsoft::MSR::CNTK::ConfigParameters,float>
    - Microsoft::MSR::CNTK::CNTKEval<float>::  CreateNetwork
    - 000007FE8F2D7D7E (SymFromAddr() error: 鎵句笉鍒版寚瀹氱殑妯″潡銆?

 Inner Exception: No Inner Exception
Press <Enter> to terminate.

thank you!

**Comment by klmsj** [comment] 2016-04-20 13:22
Comment  EvaluateModelSingleLayer()  method，the left 3 test method can sun success!

   private static void Main(string[] args)
        {
            initialDirectory = Environment.CurrentDirectory;

            Console.WriteLine("====== EvaluateModelSingleLayer ========");
            //EvaluateModelSingleLayer();

            Console.WriteLine("\n====== EvaluateModelMultipleLayers ========");
            EvaluateModelMultipleLayers();
            
            Console.WriteLine("\n====== EvaluateNetworkSingleLayer ========");
            EvaluateNetworkSingleLayer();

            Console.WriteLine("\n====== EvaluateNetworkSingleLayerNoInput ========");
            EvaluateNetworkSingleLayerNoInput();

            Console.WriteLine("Press <Enter> to terminate.");
            Console.ReadLine();
        }



console output:
====== EvaluateModelSingleLayer ========

====== EvaluateModelMultipleLayers ========

Post-processing network...

4 roots:
        ce = CrossEntropyWithSoftmax()
        err = ErrorPrediction()
        errTop5 = ErrorPrediction()
        ol.z = Plus()

Validating network. 17 nodes to process in pass 1.

Validating --> labels = InputValue() :  -> [10 x *]
Validating --> ol.W = LearnableParameter() :  -> [10 x 200]
Validating --> h1.W = LearnableParameter() :  -> [200 x 784]
Validating --> featScale = LearnableParameter() :  -> [1 x 1]
Validating --> features = InputValue() :  -> [784 x *]
Validating --> featScaled = ElementTimes (featScale, features) : [1 x 1], [784 x
 *] -> [784 x 1 x *]
Validating --> h1.t = Times (h1.W, featScaled) : [200 x 784], [784 x 1 x *] -> [
200 x 1 x *]
Validating --> h1.b = LearnableParameter() :  -> [200 x 1]
Validating --> h1.z = Plus (h1.t, h1.b) : [200 x 1 x *], [200 x 1] -> [200 x 1 x
 *]
Validating --> h1.y = Sigmoid (h1.z) : [200 x 1 x *] -> [200 x 1 x *]
Validating --> ol.t = Times (ol.W, h1.y) : [10 x 200], [200 x 1 x *] -> [10 x 1
x *]
Validating --> ol.b = LearnableParameter() :  -> [10 x 1]
Validating --> ol.z = Plus (ol.t, ol.b) : [10 x 1 x *], [10 x 1] -> [10 x 1 x *]

Validating --> ce = CrossEntropyWithSoftmax (labels, ol.z) : [10 x *], [10 x 1 x
 *] -> [1]
Validating --> err = ErrorPrediction (labels, ol.z) : [10 x *], [10 x 1 x *] ->
[1]
Validating --> unnamed81 = LearnableParameter() :  -> [1 x 1]
Validating --> errTop5 = ErrorPrediction (labels, ol.z, unnamed81) : [10 x *], [
10 x 1 x *], [1 x 1] -> [1]

Validating network. 9 nodes to process in pass 2.


Validating network, final pass.



9 out of 17 nodes do not share the minibatch layout with the input data.

Post-processing network complete.



Allocating matrices for forward and/or backward propagation.
--- Output results ---
Output layer: ol.z
0.3169661
-5.336688
0.8272594
4.336848
-3.720304
3.879937
-2.691187
-6.314416
8.442119
0.803093

====== EvaluateNetworkSingleLayer ========
NDLBuilder Using CPU

Post-processing network...

1 roots:
        ol = Plus()

Validating network. 3 nodes to process in pass 1.

Validating --> features = InputValue() :  -> [1 x *1]
Validating --> v2 = LearnableParameter() :  -> [1 x 1]
Validating --> ol = Plus (features, v2) : [1 x *1], [1 x 1] -> [1 x 1 x *1]

Validating network. 1 nodes to process in pass 2.


Validating network, final pass.



1 out of 3 nodes do not share the minibatch layout with the input data.

Post-processing network complete.



Allocating matrices for forward and/or backward propagation.
Output layer: ol
2

====== EvaluateNetworkSingleLayerNoInput ========
NDLBuilder Using CPU

Post-processing network...

1 roots:
        ol = Plus()

Validating network. 3 nodes to process in pass 1.

Validating --> v1 = LearnableParameter() :  -> [1 x 1]
Validating --> v2 = LearnableParameter() :  -> [1 x 1]
Validating --> ol = Plus (v1, v2) : [1 x 1], [1 x 1] -> [1 x 1]

Validating network. 1 nodes to process in pass 2.


Validating network, final pass.



3 out of 3 nodes do not share the minibatch layout with the input data.

Post-processing network complete.



Allocating matrices for forward and/or backward propagation.
Output layer: ol
3
Press <Enter> to terminate.

**Comment by klmsj** [comment] 2016-04-20 13:33
I change "deviceId=0" to "deviceId=-1"  in "EvaluateModelSingleLayer " method, all thing is OK!

      private static void EvaluateModelSingleLayer()
        {
            try
            {
                // The examples assume the executable is running from the data folder
                // We switch the current directory to the data folder (assuming the executable is in the <CNTK>/x64/Debug|Release folder
                Environment.CurrentDirectory = Path.Combine(initialDirectory, @"..\..\Examples\Image\MNIST\Data\");
                List<float> outputs;

                using (var model = new IEvaluateModelManagedF())
                {
                    // Initialize model evaluator
                    string config = GetFileContents(Path.Combine(Environment.CurrentDirectory, @"..\Config\01_OneHidden.cntk"));
                    model.Init(config);

                    // Load model
                    string modelFilePath = Path.Combine(Environment.CurrentDirectory, @"..\Output\Models\01_OneHidden");
                     model.CreateNetwork(string.Format("deviceId=-1\nmodelPath=\"{0}\"", modelFilePath));
                  //  model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath));

                    // Generate random input values in the appropriate structure and size
                    var inputs = GetDictionary("features", 28*28, 255);
                    
                    // We can call the evaluate method and get back the results (single layer)...
                    outputs = model.Evaluate(inputs, "ol.z", 10);
                }

                OutputResults("ol.z", outputs);
            }
            catch (CNTKException ex)
            {
                Console.WriteLine("Error: {0}\nNative CallStack: {1}\n Inner Exception: {2}", ex.Message, ex.NativeCallStack, ex.InnerException != null ? ex.InnerException.Message : "No Inner Exception");
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: {0}\nCallStack: {1}\n Inner Exception: {2}", ex.Message, ex.StackTrace, ex.InnerException != null ? ex.InnerException.Message : "No Inner Exception");
            }
        }

**Comment by klmsj** [comment] 2016-04-20 14:28
1, in a program, is all the network is either CPU, or GPU. Can not some network is CPU, the other netWork is GPU, is that right?
2, in the program set to choose CPU or GPU must be the same as the settings in the configuration file, is it?

**Comment by gaizkan** [comment] 2016-04-21 11:56
@klmsj: A couple of points:
1. You can train your model in either CPU or GPU, and run it on the same or different configuration.
2. The CSEvalProgram loads 4 networks (one at a time), but each time it should release the previous model, so the new one can be created. It seems that the previous model is not fully release, and therefore the device selection is remaining, which prevents for the next model to go from CPU to CPU (or auto).
I will investigate further.

**Comment by gaizkan** [comment] 2016-04-21 12:21
The issue is that when determining the device to use for the engine, it is stored statically, which causes the value to persist across models (within the process). So for now, as long as all the models are configured to use the same device id (CPU, GPU) the models will initialize.
Let me know if this answers your questions, and if so we can close the issue.
Best regards.

**Comment by klmsj** [comment] 2016-04-21 12:59
@gaizkan 
Yes, this is the answer I want. Thank you very much!

**Comment by gaizkan** [comment] 2016-04-21 14:20
Your welcome.
I will close the issue then.

**Closed by gaizkan** 2016-04-21 14:20 UTC
