### ISSUE TITLE
CTC layer

### ISSUE THREAD

**Issue by mzafzal** [Microsoft/CNTK#451] opened 2016-05-07 07:46 UTC
Hi
     I was just going through the speech recognition example.
     I did not see any CTC component.
     I would like to use CTC for speach recognition.
     Is there CTC component written for CNTK or at least some example which connects LSTM with CTC would be a great help!

Thanks

Shan

**Comment by mahilleb-msft** [comment] 2017-07-06 13:23
Seems a duplicate of #1491, which is resolved, please checkout there.

**Closed by mahilleb-msft** 2017-07-06 13:23 UTC
