### ISSUE TITLE
Documentation: Installing CUDA on Windows torques existing GPU drivers

### ISSUE THREAD

**Issue by DanMcLaughlin** [Microsoft/CNTK#218] opened 2016-03-09 14:21 UTC
Installing CUDA 7 on a Windows laptop (especially Win 10 with automatic updating) seriously messes with the graphics driver subsystem, also see the problem on Window 7. For example, following the [instructions](https://github.com/Microsoft/CNTK/wiki/Setup-CNTK-on-Windows) on a laptop with HD and Nvidia discrete graphics, the HD driver becomes inoperative and the Nvidia driver doesn't operate properly (some simulations crash, BSOD, etc). On a Win10 machine you get into a fight between the update system and what is installed. 

Is the driver necessary, or can it be de-selected? If it is necessary please update the instructions to indicate that CNTK should only be used on a machine with a dedicated GPGPU. If it's not necessary then the docs should indicate not to install the (old) Nvidia driver that comes with CUDA

**Comment by Alexey-Kamenev** [comment] 2016-03-09 17:03
Hi Dan,
AFAIR, the only reason why you might need to select the driver when installing CUDA is dependency on GDK. The issue is if you uncheck the driver checkbox then GDK will be disabled as well. If you have another machine where GDK is already installed then just copy it and don't install the driver that comes with CUDA toolkit.

**Comment by wolfma61** [comment] 2017-06-28 08:06
closing ...

**Closed by wolfma61** 2017-06-28 08:06 UTC
Labels: area documentation
