### ISSUE TITLE
When I test rnn.cntk, I get some ‘CUDA failure 11: invalid argument’  and ‘cannot open word class file’

### ISSUE THREAD

**Issue by wangchenwei2000** [Microsoft/CNTK#124] opened 2016-02-16 09:36 UTC
I change ptb.small.train.txt,ptb.small.valid.txt,ptb.small.test.txt，and modified confVocabSize，then cntk configFile=rnn.cntk，I face two different error in two different times

first time：

EXCEPTION occurred: cannot open word class file

second time：

CUDA failure 11: invalid argument ; GPU=0 ; hostname=DESKTOP-HP8MUOF ; expr=cudaMemcpy(ColLocation(), h_CSCCol, ColSize(), kind)
EXCEPTION occurred: CUDA failure 11: invalid argument ; GPU=0 ; hostname=DESKTOP-HP8MUOF ; expr=cudaMemcpy(ColLocation(), h_CSCCol, ColSize(), kind)

**Comment by amitaga** [comment] 2016-02-22 21:56
Are you able to run the sample successfully in its original unmodified form?

**Comment by ianupright** [comment] 2016-03-01 23:17
I'm having a similar issue, with the PennTreebank example unmodified.  I'm running Ubuntu 14.04 on a 4GB GTX 960.  I thought maybe my card had insufficient memory, so I scaled down the train model to 1024 lines, layerSizes = "$confVocabSize$:25:35:4000"
In that case I still get a similar crash at epoch 5 instead of 3 as with the former case.

DetermineSequencesToProcess: 1 sequences of len 39, 39 tokens
DetermineSequencesToProcess: 1 sequences of len 26, 26 tokens
DetermineSequencesToProcess: 1 sequences of len 25, 25 tokens
DetermineSequencesToProcess: 1 sequences of len 15, 15 tokens
DetermineSequencesToProcess: 1 sequences of len 13, 13 tokens
DetermineSequencesToProcess: 1 sequences of len 10, 10 tokens
DetermineSequencesToProcess: 0 sequences of len 0, 0 tokens
LMSequenceReader: Reading epoch data... 0 sequences read.
Final Results: Minibatch[1-3370]: Samples Seen = 73760    TrainNodeClassBasedCrossEntropy: ClassBasedCrossEntropyWithSoftmax/Sample = 5.212208    Perplexity = 183.49877    
Finished Epoch[ 3 of 16]: [Validation Set] TrainLossPerSample = 5.212208
Loading previous model with best training-criterion value: ../Output/Models/rnn.dnn.2.
learnRatePerSample reduced to 0.050000001
SGD: Saving checkpoint model '../Output/Models/rnn.dnn.3'
Starting Epoch 4: learning rate per sample = 0.050000  effective momentum = 0.000000  momentum as time constant = 0.0 samples

Starting minibatch loop.
LMSequenceReader: Reading epoch data... 2157 sequences read.
DetermineSequencesToProcess: 10 sequences of len 11, 110 tokens

[CALL STACK]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::CollectCallStack(std::function<void (std::string)> const&, std::function<void ()> const&)  + 0x101 )  [0x7fb67014c401]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::PrintCallStack()  + 0x88  )  [0x7fb67014c898]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::runtime_error>(char const*, ...)  + 0xe2  )  [0x541902]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so (                                           + 0x29d317)  [0x7fb6700ff317]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::GPUSparseMatrix<double>::SetValue(Microsoft::MSR::CNTK::CPUSparseMatrix<double> const&)  + 0x88  )  [0x7fb670116e58]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix<double>::_transferFromDeviceToDevice(int, int, bool, bool) const  + 0x4c1 )  [0x7fb67003d3a1]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix<double>::TransferFromDeviceToDevice(int, int, bool, bool, bool) const  + 0x18  )  [0x7fb67003d8c8]
  /usr/local/cntk/build/release/bin/../lib/LMSequenceReader.so ( Microsoft::MSR::CNTK::BatchSequenceReader<double>::GetMinibatch(std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&)  + 0x4f7 )  [0x7fb65d55e1b7]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DataReader<double>::GetMinibatch(std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&)  + 0x61  )  [0x7fb670145661]
  cntk                           ( bool Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<double>(Microsoft::MSR::CNTK::IDataReader<double>&, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, bool, bool, std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&, unsigned long&)  + 0x57  )  [0x722787]
  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::TrainOneEpoch(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&, int, unsigned long, Microsoft::MSR::CNTK::IDataReader<double>*, double, unsigned long, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::map<std::basic_string<wchar_t,  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::TrainOrAdaptModel(int, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, bool, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, Microsoft::MSR::CNTK::IDataReader<double>*, Microsoft::MSR::CNTK::IDataReader<double>*)  + 0x1218)  [0x72b338]
  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<double>*, Microsoft::MSR::CNTK::IDataReader<double>*, bool)  + 0x424 )  [0x72d184]
  cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, double>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x22c )  [0x74df4c]
  cntk                           ( void DoCommands<double>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x804 )  [0x598814]
  cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0xad1 )  [0x53b421]
  cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53b8b0]
  cntk                           ( main                                      + 0xd8  )  [0x530598]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7fb66ed9bec5]
  cntk                           (                                                   )  [0x534364]
CUDA failure 11: invalid argument ; GPU=0 ; hostname=s02 ; expr=cudaMemcpy(ColLocation(), h_CSCCol, ColSize(), kind)
EXCEPTION occurred: CUDA failure 11: invalid argument ; GPU=0 ; hostname=strong02.cluster.semanticideas.com ; expr=cudaMemcpy(ColLocation(), h_CSCCol, ColSize(), kind)

----

error with smaller model size:

DetermineSequencesToProcess: 1 sequences of len 30, 30 tokens
DetermineSequencesToProcess: 1 sequences of len 18, 18 tokens
DetermineSequencesToProcess: 1 sequences of len 15, 15 tokens
DetermineSequencesToProcess: 1 sequences of len 16, 16 tokens
DetermineSequencesToProcess: 1 sequences of len 12, 12 tokens
DetermineSequencesToProcess: 1 sequences of len 14, 14 tokens
DetermineSequencesToProcess: 0 sequences of len 0, 0 tokens
LMSequenceReader: Reading epoch data... 0 sequences read.
Final Results: Minibatch[1-32]: Samples Seen = 722    TrainNodeClassBasedCrossEntropy: ClassBasedCrossEntropyWithSoftmax/Sample = 5.3909358    Perplexity = 219.40862    
Finished Epoch[ 5 of 16]: [Validation Set] TrainLossPerSample = 5.3909358
Loading previous model with best training-criterion value: ../Output/Models/rnn.dnn.4.
learnRatePerSample reduced to 0.050000001
SGD: Saving checkpoint model '../Output/Models/rnn.dnn.5'
Starting Epoch 6: learning rate per sample = 0.050000  effective momentum = 0.000000  momentum as time constant = 0.0 samples

Starting minibatch loop.
LMSequenceReader: Reading epoch data... 1024 sequences read.
DetermineSequencesToProcess: 10 sequences of len 10, 100 tokens

[CALL STACK]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::CollectCallStack(std::function<void (std::string)> const&, std::function<void ()> const&)  + 0x101 )  [0x7fd304b4a401]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::ExceptionWithCallStack<std::runtime_error>::PrintCallStack()  + 0x88  )  [0x7fd304b4a898]
  cntk                           ( void Microsoft::MSR::CNTK::ThrowFormatted<std::runtime_error>(char const*, ...)  + 0xe2  )  [0x541902]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so (                                           + 0x29d317)  [0x7fd304afd317]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::GPUSparseMatrix<double>::SetValue(Microsoft::MSR::CNTK::CPUSparseMatrix<double> const&)  + 0x88  )  [0x7fd304b14e58]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix<double>::_transferFromDeviceToDevice(int, int, bool, bool) const  + 0x4c1 )  [0x7fd304a3b3a1]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::Matrix<double>::TransferFromDeviceToDevice(int, int, bool, bool, bool) const  + 0x18  )  [0x7fd304a3b8c8]
  /usr/local/cntk/build/release/bin/../lib/LMSequenceReader.so ( Microsoft::MSR::CNTK::BatchSequenceReader<double>::GetMinibatch(std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&)  + 0x4f7 )  [0x7fd2f1f1a1b7]
  /usr/local/cntk/build/release/bin/../lib/libcntkmath.so ( Microsoft::MSR::CNTK::DataReader<double>::GetMinibatch(std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&)  + 0x61  )  [0x7fd304b43661]
  cntk                           ( bool Microsoft::MSR::CNTK::DataReaderHelpers::GetMinibatchIntoNetwork<double>(Microsoft::MSR::CNTK::IDataReader<double>&, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, bool, bool, std::map<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, Microsoft::MSR::CNTK::Matrix<double>*, std::less<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > >, std::allocator<std::pair<std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const, Microsoft::MSR::CNTK::Matrix<double>*> > >&, unsigned long&)  + 0x57  )  [0x722787]
  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::TrainOneEpoch(std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> const&, int, unsigned long, Microsoft::MSR::CNTK::IDataReader<double>*, double, unsigned long, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::vector<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, std::allocator<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase> > > const&, std::map<std::basic_string<wchar_t,  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::TrainOrAdaptModel(int, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, bool, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork>, std::shared_ptr<Microsoft::MSR::CNTK::ComputationNodeBase>, Microsoft::MSR::CNTK::IDataReader<double>*, Microsoft::MSR::CNTK::IDataReader<double>*)  + 0x1218)  [0x72b338]
  cntk                           ( Microsoft::MSR::CNTK::SGD<double>::Train(std::function<std::shared_ptr<Microsoft::MSR::CNTK::ComputationNetwork> (int)>, int, Microsoft::MSR::CNTK::IDataReader<double>*, Microsoft::MSR::CNTK::IDataReader<double>*, bool)  + 0x424 )  [0x72d184]
  cntk                           ( void DoTrain<Microsoft::MSR::CNTK::ConfigParameters, double>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x22c )  [0x74df4c]
  cntk                           ( void DoCommands<double>(Microsoft::MSR::CNTK::ConfigParameters const&)  + 0x804 )  [0x598814]
  cntk                           ( wmainOldCNTKConfig(int, wchar_t**)        + 0xad1 )  [0x53b421]
  cntk                           ( wmain1(int, wchar_t**)                    + 0x70  )  [0x53b8b0]
  cntk                           ( main                                      + 0xd8  )  [0x530598]
  /lib/x86_64-linux-gnu/libc.so.6 ( __libc_start_main                         + 0xf5  )  [0x7fd303789ec5]
  cntk                           (                                                   )  [0x534364]

**Comment by ianupright** [comment] 2016-03-01 23:34
Interestingly enough, even at 5 epochs the CPU is several times faster than the GPU.  Why would this be?

**Comment by frankseide** [comment] 2016-03-01 23:45
This may be Issue #177 (numeric overflow in gcc build due to different value of RAND_MAX on VS vs. gcc). In some cases, this led to shuffling data from out of bounds.

In SequenceReader.cpp: BatchSequenceReader<ElemType>::GetMinibatchData() could you please try to replace the second random_shuffle() call by std::shuffle() like below.

#ifdef _MSC_VER // make some old configurations reproducable (m_cacheBlockSize used to be a constant)  --TODO: remove in a few months
        if (m_cacheBlockSize == 50000)
        {
            std::random_shuffle(m_parser.mSentenceIndex2SentenceInfo.begin(), m_parser.mSentenceIndex2SentenceInfo.end());
            // Note: random_shuffle is deprecated since C++14.
        }
        else // new configs use a wider randomization
#endif
        {
            std::random_device rd;
            std::mt19937 g(rd());
            std::shuffle(m_parser.mSentenceIndex2SentenceInfo.begin(), m_parser.mSentenceIndex2SentenceInfo.end(), g);
        }

**Comment by ianupright** [comment] 2016-03-02 00:36
I think you mean #176. Unfortunately that didn't seem help.  Since it is at the very beginning of initializing a new epoch it wouldn't seem to be a random problem with the SequenceReader

**Comment by ianupright** [comment] 2016-03-02 01:52
I pulled the very latest code, released just in the last few days.  After rebuilding this problem has gone away.

**Comment by frankseide** [comment] 2016-03-02 02:56
Yes, it just got committed. If the problem is solved, would you mind closing the Issue?

Thanks!

Frank

**Comment by frankseide** [comment] 2016-03-02 03:28
Fixed. Thanks for the report and for helping to track it down!

**Closed by frankseide** 2016-03-02 03:28 UTC
Labels: question
