### ISSUE TITLE
Attention Model not working properly..?

### ISSUE THREAD

**Issue by tomasek** [Microsoft/CNTK#2675] opened 2017-11-25 13:57 UTC
I have been working with sequence to sequence and I have based my work on the CNTK_204 tutorial. After many attempts with more than 50 epochs each, the output of the attention layer is always:
`[[ 0.33333  0.33333  0.33333]
 [ 0.33333  0.33333  0.33333]]`
And the output label is always the same too. 
Moreover, it happens with both my code and the tutorial code.
Is there any known issue? Or am I just doing something wrong?

**Comment by tomasek** [comment] 2017-11-28 17:30
Let me be a bit more clear: It works fine up to 3 hidden layers and 512 hidden dimensions. After some testing, i believe that above 512 hidden dimensions, the Attention Model stops updating the weights.

**Comment by n17s** [comment] 2017-12-02 01:03
The fact that it is working with 3 layers and 512 dimensions suggests that this is not a bug  in how CNTK works but some form of bad network specification (there is nothing that is hardcoded to 3 layers or fewer than 512 hidden dimensions). E.g. you might be using a too small learning rate or have somehow saturated the non-linearities in the network which makes the gradients extremely small.

I'm closing this since this is not an issue about how CNTK should work.

**Closed by n17s** 2017-12-02 01:03 UTC
