### ISSUE TITLE
EvalWrapper outputting different layers

### ISSUE THREAD

**Issue by PatrickBue** [Microsoft/CNTK#539] opened 2016-05-31 21:08 UTC
Hi,
I am using the EvalWrapper ("EvaluateModelSingleLayer" function) to run a model in C# and return the last layer. Is it possible to also (or instead) return e.g. the second-to-last layer?
I guess using dedicated .cntk/.mel files would work, but is there an easier way eg doing this programmatically?
Thanks,
Patrick

**Comment by gaizkan** [comment] 2016-06-01 08:15
Hi Patrick,

Yes, you can change which nodes are marked as "output" nodes. The quick answer is add "outputNodeNames=<node>:<node>" as a prefix to your model description.

Refer to https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluate-Hidden-Layers for a more detailed explanation. Since you are using the EvalWrapper, you might just need the last section (3. Modifying an already trained model while loading it for evaluation using the EvalDLL/EvalWrapper modules).

I am in the process of extending the EvalWrapper to do this behind-the-scenes, where you can call the CreateNetwork with an additional parameter consisting of a list of output nodes. This code should be in the repository hopefully by the end of the week.

Thanks,
Gaizka

**Comment by PatrickBue** [comment] 2016-06-01 15:03
Hi Gaizka,
Thanks for your help! I added the outputNodeNames=<..> string and it works like a charm.

**Comment by gaizkan** [comment] 2016-06-03 06:33
I am assuming the issue is closed. Let me know otherwise.

**Closed by gaizkan** 2016-06-03 06:33 UTC
