### ISSUE TITLE
training_session().train() not ending

### ISSUE THREAD

**Issue by aFuerst** [Microsoft/CNTK#1639] opened 2017-03-20 22:47 UTC
After calling train() on a TrainingSession object I created with training_session() it never seems to finish training and I get output that looks like this:
Finished Epoch[936 of 300]: loss = 0.000055 * 512, metric = 0.00% * 512 0.662s (773.4 samples/s);

Here is how I create and initiate the training session:
ts = c.train.training_session(trainer=trainer, mb_source=reader_train,
                              mb_size=schedule, progress_printer=progress_printer, restore=True,
                              progress_frequency=training_progress_output_freq, var_to_stream=input_map,
                              checkpoint_config=CheckpointConfig(filename=os.path.join(model_path, model_name)),
                              cv_config=CrossValidationConfig(source=reader_train, mb_size=minibatch_size))

ts.train()

None of the parameters seem to refer to number of Epochs or stopping when the error rate hits some threshold

**Comment by eldakms** [comment] 2017-03-21 08:08
Hi aFuerst,

You can provide "max_samples" to the training session or when you create the minibatch source (reader_train in your case) - you can also specify the max number of samples. In the upcoming beta you will be able to specify the number of sweeps, not only number of samples in the minibatch source.

**Comment by aFuerst** [comment] 2017-03-21 14:31
Adding max_samples to training_session or epoch_size to MinibatchSource both cause this error when I call train()

  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py", line 63, in wrapper
    result = f(*args, **kwds)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\train\training_session.py", line 167, in train
    super(TrainingSession, self).train(device)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2528, in train
    return _cntk_py.TrainingSession_train(self, computeDevice)
ValueError: Attempting to accumulate a null Value.

**Comment by eldakms** [comment] 2017-03-21 14:48
Could you please post your script - or send it directly at eldak at microsoft dot com? Thanks!

**Comment by aFuerst** [comment] 2017-03-21 15:25
from __future__ import print_function
import numpy as np
import os

import cntk as c
import cntk.io.transforms as xforms
from cntk.ops import input_variable
from cntk import Trainer, learning_rate_schedule, UnitType, CheckpointConfig, CrossValidationConfig
from cntk.io import ImageDeserializer, MinibatchSource, StreamDef, StreamDefs
#  from cntk.io import INFINITELY_REPEAT, FULL_DATA_SWEEP
from cntk.initializer import glorot_uniform
from cntk.layers import default_options, Dense
from cntk.learner import sgd
from cntk.logging import *

c.device.set_default_device(c.device.gpu(0))

np.random.seed(0)

mean_file = os.path.join("..", "train_mean.xml")
training_file = os.path.join("..", "training.txt")
testing_file = os.path.join("..", "testing.txt")

if not os.path.isfile(training_file):  # confirm training file exists where it should be
    raise ValueError("Data file not found")
else:
    num_lines = sum(1 for line in open(training_file))
    print("File found at: {}, Num Objects: {}".format(training_file, num_lines))

if not os.path.isfile(mean_file):  # confirm mean file exists where it should be
    raise ValueError("Mean file not found")
else:
    print("File found at: {}".format(mean_file))


def create_reader(path, is_training, num_label_classes):
    #  transformation pipeline for the features has jitter/crop only when training
    transforms = []
    if is_training:
        transforms += [
            xforms.crop(crop_type='randomside', side_ratio=0.8)  # train uses data augmentation (translation only)
        ]
        transforms += [
            xforms.scale(width=200, height=200, channels=input_dim_channels, interpolations='linear'),
            xforms.mean(mean_file)
        ]

    # Read a CTF formatted text (as mentioned above) using the CTF deserializer from a file
    return MinibatchSource(ImageDeserializer(path, StreamDefs(
        labels=StreamDef(field='label', shape=num_label_classes),
        features=StreamDef(field='image', transforms=transforms)
    )), epoch_size=c.io.FULL_DATA_SWEEP)


def create_network(features, hidden_layers):
    with default_options(init=glorot_uniform(), activation=c.ops.relu):
        h = features
        # h = Convolution((5, 5), 32, init=glorot_uniform(), activation=c.ops.relu, pad=True)(h)
        for qwerty in range(hidden_layers):
            h = Dense(hidden_layer_dim)(h)
        r = Dense(output_classes, activation=None)(h)
        return r

# script constants
input_dim_x = 200
input_dim_y = 200
input_dim = input_dim_x * input_dim_y
input_dim_channels = 3
output_classes = 2
num_hidden_layers = 10
hidden_layer_dim = 1000

input_layer = input_variable((input_dim_channels, input_dim_x, input_dim_y))
label = input_variable(output_classes)

# scale input values to between 0-1
z = create_network(input_layer/256.0, num_hidden_layers)

loss = c.ops.cross_entropy_with_softmax(z, label)
label_error = c.ops.classification_error(z, label)

learning_rate = .2
learner_schedule = learning_rate_schedule(learning_rate, UnitType.minibatch)
learner = sgd(z.parameters, learner_schedule)

trainer = Trainer(z, (loss, label_error), [learner])

# Initialize the parameters for the trainer
minibatch_size = 64

# Create the reader to training data set
reader_train = create_reader(training_file, True, output_classes)

# Map the data streams to the input and labels.
input_map = {
    label: reader_train.streams.labels,
    input_layer: reader_train.streams.features
}

# Run the trainer on and perform model training
training_progress_output_freq = 500

progress_printer = ProgressPrinter(freq=training_progress_output_freq)
schedule = c.train.minibatch_size_schedule([(12, 32), (15, 64), (1, 128)], minibatch_size)

model_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
model_name = "peopleMatcher"

print("Starting training")
ts = c.train.training_session(trainer=trainer, mb_source=reader_train,  # max_samples=10,
                              mb_size=schedule, progress_printer=progress_printer, restore=True,
                              progress_frequency=training_progress_output_freq, var_to_stream=input_map,
                              checkpoint_config=CheckpointConfig(filename=os.path.join(model_path, model_name)),
                              cv_config=CrossValidationConfig(source=reader_train, mb_size=minibatch_size))
ts.train()

print("stopped training")
`

**Comment by aFuerst** [comment] 2017-03-21 15:29
I've noticed that it occurs when I run the script a second time and it loads the saved checkpoint from a file. But if I put the training in a loop it doesn't appear to perform any additional training.

```
for i in range(5):
    ts = c.train.training_session(trainer=trainer, mb_source=reader_train,  # max_samples=10,
                                  mb_size=schedule, progress_printer=progress_printer, restore=True,
                                  progress_frequency=training_progress_output_freq, var_to_stream=input_map,
                                  checkpoint_config=CheckpointConfig(filename=os.path.join(model_path, model_name)),
                                  cv_config=CrossValidationConfig(source=reader_train, mb_size=minibatch_size))
    ts.train()
```

It just keeps saying:
Restoring training session from the checkpoint

**Comment by eldakms** [comment] 2017-03-21 15:40
You do not run training session in a loop.
ts.train runs till the end of the data that minibatch source is providing. Then it takes the checkpoint. If you then run it again - it won't do anything because you already reached the end of data.

I will have a look where ValueError is coming from.

**Comment by eldakms** [comment] 2017-03-22 16:48
Thank you very much for reporting this!
I was able to reproduce the ValueError - this has been fixed on eldak/fixingAccError, will be integrated to master shortly and will be available in the next release (or you can build from my branch).

Now if I run with max_samples = 10, I got:

In case when no checkpoints exists:
![image](https://cloud.githubusercontent.com/assets/12430061/24209796/87c00e3a-0f27-11e7-803e-91a4ca3c7ae8.png)

In case when there are checkpoints:
![image](https://cloud.githubusercontent.com/assets/12430061/24209839/a70d8a1a-0f27-11e7-81b9-de0aa8a12861.png)

**Comment by eldakms** [comment] 2017-03-22 16:48
I am closing the issue for now, feel free to reopen if you bump into something. Thanks!

**Closed by eldakms** 2017-03-22 16:48 UTC

**Comment by dashesy** [comment] 2017-09-11 20:13
@eldakms What is the point of providing `total_number_of_samples` to the source if it comes from let's say a text file? I also encountered something similar to `Finished Epoch[936 of 300]:` and was baffled why `training_session` did not end already! 
The problem with passing `total_number_of_samples` is that we will need to parse the input just to figure that out, instead of leaving that to the input stream parser.
