### ISSUE TITLE
vector<T> too long exception occurs when using C++ API

### ISSUE THREAD

**Issue by taeguk-sualab** [Microsoft/CNTK#1317] opened 2017-01-19 09:04 UTC
I develop c++ program using CNTK C++ API by linking with CNTKLibrary-2.0.lib.
I install https://github.com/Microsoft/CNTK/releases/tag/v2.0.beta8.0 (CNTK for Windows v.2.0 Beta 8 GPU)

#### This problem occurs in only Debug mode, not Release mode.

----environments----
Windows 10
Visual studio 2015 Update 3
CUDA 8.0
cudnn 5.1

![image](https://cloud.githubusercontent.com/assets/25145844/22100106/70943614-de71-11e6-8836-dec53412c9e4.png)

When in line 12, change 2->200, "string too long" exception occurs.
![image](https://cloud.githubusercontent.com/assets/25145844/22100268/34c72ed8-de72-11e6-8f59-aaf0fd59ea4e.png)

**Comment by eldakms** [comment] 2017-01-19 09:08
Are you linking in debug project release dll? 
if you develop against c++ dll/lib, your runtime should currently match. Try switching your project to release.
Thanks!

**Comment by taeguk-sualab** [comment] 2017-01-19 09:38
@eldakms I built in debug mode with debug lib (cntk\x64\Debug)...

**Comment by eldakms** [comment] 2017-01-19 09:44
Did you build CNTKLibrary-2.0.dll yourself in debug mode? If you open Modules window in VS before this assert files, do you see the debug version of dll loaded as you would expect (check the path)? 
If you installed from the official binary drop - everything is release there.
Thanks!

**Comment by taeguk-sualab** [comment] 2017-01-19 09:47
@eldakms I build CNTKLibrary-2.0.lib myself in VS2015 debug/x64 mode.

**Comment by taeguk-sualab** [comment] 2017-01-19 09:54
![image](https://cloud.githubusercontent.com/assets/25145844/22101715/ee37460a-de77-11e6-9315-0af6a14d7793.png)

![image](https://cloud.githubusercontent.com/assets/25145844/22101890/a31ab390-de78-11e6-8a09-9782c91ff75b.png)
![image](https://cloud.githubusercontent.com/assets/25145844/22101878/9387a0e6-de78-11e6-8422-d119c0a667c5.png)

I check all paths are right.

**Comment by eldakms** [comment] 2017-01-19 09:54
Hm, I cannot reproduce this on my machine (though i'm on latest master).
Could you please insert the Modules output for CNTKLibrary-2.0.dll here? Thank you!

![image](https://cloud.githubusercontent.com/assets/12430061/22101916/ae47518a-de35-11e6-936f-c6b744b449fa.png)

**Comment by taeguk-sualab** [comment] 2017-01-19 10:01
@eldakms My dll path indicated Release. Very sorry... I thought only .lib is needed to my program. So, I didn't know dll was loaded. But, because of your kindness, I got it. Thank you so much!

**Comment by eldakms** [comment] 2017-01-19 10:01
Sure, no problem! Closing the issue.

**Closed by eldakms** 2017-01-19 10:01 UTC
