### ISSUE TITLE
LSTM model changing with first eval batch

### ISSUE THREAD

**Issue by jakrivan** [Microsoft/CNTK#2977] opened 2018-02-20 10:23 UTC
Is it expected and needed to change the model during the evaluation?
What exactly is being changed in the model during the evaluation?

**Background:**

We do expect the CNTK model byte representation (CNTK.Trainer.Model().Save() in C#) to change only when the model is actualy changing (during training). This also enables us to simply check equivalence of models; verify that model is not touched by training when it's not supposed to be etc. - those checks can be performed by same code harness that doesn't depend on actual implementation of training/evaluation process.

This seemed to work fine, until recently where we found that LSTM model is changing with first batch being evaluated (then stays unchanged for other batches).
Full repro is attached: [SaveDiscrepancyRepro_cs.txt](https://github.com/Microsoft/CNTK/files/1743317/SaveDiscrepancyRepro_cs.txt)

Here are the few lines demonstrating the core of the issue:

            //Save the model before evaluation
            var pre = tr.Model().Save();

            tr.Model().Evaluate(data, outputDataMap, device);

            //Save the model after evaluation
            var post = tr.Model().Save();

            var differ = Enumerable.Range(0, pre.Length).Where(j => pre[j] != post[j]).ToArray();

            if (differ?.Length > 0)
            {
                throw new Exception("Saved models pre and post evaluation differ in " + differ.Length.ToString() +
                                    " bytes.");
            }

**Comment by KeDengMS** [comment] 2018-02-21 07:05
Thanks for the report. Could you provide the model being loaded before eval?

**Comment by jakrivan** [comment] 2018-02-21 08:44
@KeDengMS Thanks for looking in.

My appology for forgotting to attach the full repro.
I have now attached it to the original question. 
It's self containing - you just need to add to a project referencing Cntk.Core.Managed-2.3 and run SaveDiscrepancyRepro.Test()

Let me know if different type of repro would be more suitable.

**Comment by KeDengMS** [comment] 2018-02-23 21:27
Thanks for the detailed repro. I inspected the model before and after eval and all parameters have the same weight, so this difference does not affect eval accuracy. The root cause of the change is because:
1. With C#/Python, CNTK builds a V2 computation graph
2. Because V2 and V1 (BrainScript) shares lots of computation nodes, two V1 graphs are constructed separately when TrainMinibatch() and Eval()
3. V1 graph is cached in trainer and function.Eval() respectively, because user may eval from any functions in the middle of the graph
4. Some node names are generated differently in these two V1 graphs

So if you call Eval() again, the model saved would not change. I'll close the issue for now, and there'll be more consistency when we redesign CNTK's graph representation.

**Closed by KeDengMS** 2018-02-23 21:27 UTC

**Comment by jakrivan** [comment] 2018-02-25 20:05
@KeDengMS Thanks for the explanation.

Is there any way how to force V1 graph construction without call to eval?

We have external testing harness that needs to verify that serialized model doesn't change when it's not expected to change (which is - during the phase when only eval is called)

**Comment by KeDengMS** [comment] 2018-02-28 22:05
Can you call eval once before Save()? After eval the V1 graph would be cached and you'll get identical models in Save() later.

**Comment by jakrivan** [comment] 2018-03-01 07:39
If there is no other option than I'll have to.
I was hoping for some quick call, without need for parameter preparation.. If there is non, than I'll simply take the firs sequence of train batch and will call eval on that.

**Comment by KeDengMS** [comment] 2018-03-05 20:14
That should work. I'll close the issue for now and feel free to reopen if you run to other unexpected issues wrt. model saving.

**Comment by jakrivan** [comment] 2018-03-06 12:37
Thanks,
Yes - you can consider resolved (I used the dummy eval method to force the V1 graph creation)
