### ISSUE TITLE
cntk nuget packages

### ISSUE THREAD

**Issue by aluplaetter** [Microsoft/CNTK#1707] opened 2017-04-05 08:15 UTC
The nuget packages have some error in(the online version), so it's not possible to build some projects with nuget(cntk\Examples\Evaluation\CNTKLibraryCSEvalGPUExamples).

Severity	Code	Description
Error	CS1501	No overload for method 'CreateSequence' takes 7 arguments

if i compile the managed dll self, everything works as expected. Only downloading with nuget makes the compilererror.

Also there is a problem with the version numbers "beta15" is voted as a lower version as "beta9". "rc1" is voted as newer as "beta15".

**Comment by zhouwangzw** [comment] 2017-04-05 08:38
@aluplaetter Have you updated your Nuget package to 2.0RC1? We added support for sparse input, so the examples in RC1 contain code samples how to use sparse input with CreateSequence(), which cannot be compiled with older Nuget package versions e.g. "beta15".

Regarding version issue, it is due to that Nuget 2 does not support semantic versioning 2.0, so it lists "beta15" as a lower version than "beta9" (string comparison, but not numeric comparison). RC1 is the latest version.

Thanks,

**Comment by aluplaetter** [comment] 2017-04-05 11:16
No
I used beta15
So thanks i will try with rc1.

Greetings
Robert Franz

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Zhou Wang<mailto:notifications@github.com>
Gesendet: Mittwoch, 5. April 2017 10:39
An: Microsoft/CNTK<mailto:CNTK@noreply.github.com>
Cc: aluplaetter<mailto:robert@franz.name>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [Microsoft/CNTK] cntk nuget packages (#1707)


@aluplaetter<https://github.com/aluplaetter> Have you updated your Nuget package to 2.0RC1? We added support for sparse input, so the examples in RC1 contain code samples how to use sparse input with CreateSequence(), which cannot be compiled with older Nuget package versions e.g. "beta15".

Regarding version issue, it is due to that Nuget 2 does not support semantic versioning 2.0, so it lists "beta15" as a lower version than "beta9" (string comparison, but not numeric comparison). RC1 is the latest version.

Thanks,

**Comment by KolyaIvankov** [comment] 2017-05-04 09:53
Since the issue is not closed, I'd like to mention here that the current NuGet 2.0rc2 package seems not to contain Cntk.Eval-2.0rc2.dll in 

\CNTK.CPUOnly.2.0.0-rc2\support\x64\Release 

folder, I've had to add it manually from Microsoft.Research.CNTK.CpuEval-mkl.2.0.0-rc2 .

**Comment by zhouwangzw** [comment] 2017-05-04 10:05
@KolyaIvankov The Nuget packages CNTK.CPUOnly and CNTK.GPU are for CNTKLibrary C# Eval, the new API based on CNTK Library API described [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows), and thus does not contain Cntk.Eval-2.0rc2.dll. The Microsoft.Research.CNTK.CpuEval-mkl.2.0.0-rc2 implements the "old" EvalDLL based eval API as described [here](https://github.com/Microsoft/CNTK/wiki/EvalDll-Evaluation-on-Windows), which uses Cntk.Eval-2.0rc2.dll. 
Depending on which API you are using, the corresponding Nuget package should be installed. An overview of different methods for Eval are explained [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview). We recommend to use the new CNTK Library API (using Nuget package CNTK.CPUOnly or CNTK.GPU), if you have not used the "old" EvalDll API in your application, because the new API provides more features like GPU support and better multi-threads support.

**Comment by KolyaIvankov** [comment] 2017-05-04 10:11
@zhouwangzw 
Thanks, I've had two projects in the solution that used CNTK, and didn't install the newer version for one of them. This should have have caused the problem.

**Comment by zhouwangzw** [comment] 2017-05-11 11:21
Glad to know that the problem is resolved. I am closing the issue. Please feel free to reopen it if needed.

**Closed by zhouwangzw** 2017-05-11 11:21 UTC
