### ISSUE TITLE
CNTK crashes python when transposing a vector

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/CNTK#1535] opened 2017-02-26 11:22 UTC
A library should never crash python.
```
import cntk as c

parameter = c.parameter(shape=(5))
transposed = c.transpose(parameter)
print(transposed.shape)
```

**Comment by sayanpa** [comment] 2017-07-13 01:54
On V2 does not crash. Gives an error. Please let us know if this repro's on your setup. Closing this issue as the issue is fixed.

**Closed by sayanpa** 2017-07-13 01:54 UTC
