### ISSUE TITLE
Does Cntktextformatreader support context window to the input samples?

### ISSUE THREAD

**Issue by newoneincntk** [Microsoft/CNTK#509] opened 2016-05-22 07:19 UTC
In the HTKMLFReader, an integer that specifies the full feature vector dimension with the desired context window. For example, if you had 72-dimensional features (24-dimensional filterbank features plus delta and delta-delta coefficients) and the network is designed to process a context window of 11 frames, the specified dimension should be 792.
Does Cntktextformatreader have similar function? Or How to read the 72-dimensional features with different context window size when I use Cntktextformatreader?

**Comment by cmarschner** [comment] 2016-05-23 13:05
CNTKTextFormatReader is by design not very smart. It takes the tensors that are presented to the reader and feeds them in - nothing more. If you want to feed a context, you would have to turn that into input data upfront.

**Comment by mahilleb-msft** [comment] 2017-07-07 08:24
Closing this issue as answered (and dormant for a long while). Please file a new issue if necessary.
Thanks!

**Closed by mahilleb-msft** 2017-07-07 08:24 UTC
