### ISSUE TITLE
require CTC example with pythin API

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1983] opened 2017-06-08 21:00 UTC
Hi

I try to migrate to python API as the ndl/mel script getting out of dated. I try to use `forward_backward` as my criterion and `edit_distance_error` as my classification error measure. I used them highly similar to [this](https://github.com/Microsoft/CNTK/blob/master/Tests/EndToEndTests/Speech/LSTM_CTC_MLF/lstm.bs) example, except compulsory python API differences (for example tokensToIgnore should be a list contains blank token). My snippet code for CTC is as follow:

```
    graph = labels_to_graph(labels)
    cr = forward_backward(graph, L3, 132)
    err = edit_distance_error(labels, L3, squashInputs=True, tokensToIgnore=[132])
```
which L3 is the network output, But it thrown a runtime exception:

> Traceback (most recent call last):
  File "an4_ctc_example.py", line 76, in <module>
    trainer.train_minibatch(mb)
  File "/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/train/trainer.py", line 170, in train_minibatch
    arguments, device)
  File "/home/aj/anaconda3/envs/cntk-py27/lib/python2.7/site-packages/cntk/cntk_py.py", line 2500, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: SetDataLocation [CPUMatrix]: Cannot migrate the matrix between devices because it is a view.

when I use my GPU, while using CPU cause another error:

> *** Error in `python': free(): invalid next size (normal): 0x000000000398c790 ***
Aborted (core dumped)

please help me with this error. @vmazalov 

regards

**Comment by DabiaoMa** [comment] 2017-06-09 02:06
Is this function ' ce = forward_backward() '  the loss function of CTC training, which means I can do something like ' trainer = cntk.Trainer( output,  ce,  learner)'???

**Comment by vmazalov** [comment] 2017-07-06 17:35
Closing as a duplicate of issue #2079

**Closed by vmazalov** 2017-07-06 17:35 UTC
