### ISSUE TITLE
Runtime exception at ModelEvaluationExtendedF()

### ISSUE THREAD

**Issue by SourabhMakker** [Microsoft/CNTK#1695] opened 2017-04-03 13:53 UTC
I am new to cntk code. I added cntk nuget to VS 2013 framework 4.5 X64. The code below compiles successfully but gives runtime exception at like  new ModelEvaluationExtendedF()

Please help me understand if I am missing anything critical here.

An exception of type 'System.Runtime.InteropServices.SEHException' occurred in EvalWrapper.dll but was not handled in user code

Code:
ModelEvaluationExtendedF a = new ModelEvaluationExtendedF();
                //using (var model = new ModelEvaluationExtendedF())
                //{
                //    //string modelFilePath = @"..\..\..\..\CNTK_StrategySel\Models\Trained_StrategySel_Model.dnn";
                //    //model.CreateNetwork(string.Format("modelPath=\"{0}\"", modelFilePath), -1);

                //    //List<double> periodFeatures = new List<double>();
                //    //for (int i = 0; i < 5; i++)
                //    //{
                //    //    periodFeatures.Add(1);
                //    //}

                //    //var inputs = new Dictionary<string, List<double>>();
                //    //inputs.Add("features", periodFeatures);

                //    //List<double> outputs = new List<double>();
                //    //List<List<double>> checker = new List<List<double>>();
                //    //for (int i = 0; i < 5; i++)
                //    //{
                //    //    outputs = model.Evaluate(inputs, "activation");
                //    //    checker.Add(outputs);
                //    //}

                //    Console.WriteLine("Finish");
                //}

**Comment by zhouwangzw** [comment] 2017-04-04 06:57
The error is usually caused by that some dependent dlls of EvalDll are missing or not in the search path of Dlls in Windows. The dlls that EvalDll requires are listed [here](https://github.com/Microsoft/CNTK/wiki/EvalDll-Evaluation-on-Windows#shipping-evaldll-library-with-your-windows-application). Please note the page lists dll names used in the latest 2.0RC1. If you are using an older version, you can find the mapping of file names [here](https://github.com/Microsoft/CNTK/wiki/CNTK-Shared-Libraries-Naming-Format).

Another thing I noticed is that you are using EvalDll when when creating network, i.e. ModelEvaluationExtendedF()  and model.CreateNetwork(), but the code listed in the box is using CNTK Library API, e.g. model.Evaluate(). Please note that EvalDll (which is known as V1 Eval) is not compatible with CNTKLibrary (which is known as V2). You can find description in this [wiki page](https://github.com/Microsoft/CNTK/wiki/CNTK-Evaluation-Overview). You can use either of them, but not in a mixed way. We recommend to use the [new CNTKLibrary API]. (https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Evaluation-on-Windows).

**Comment by SourabhMakker** [comment] 2017-04-04 11:17
Hello, Thanks for the revert. Unfortunately the issue still exists.

**I have installed below nuget package:**

![image](https://cloud.githubusercontent.com/assets/26872587/24654104/f370bcee-18fd-11e7-9e30-d2b4abb35069.png)

**This is the code example taken from Github
As is CSEvalClient Code:**

![image](https://cloud.githubusercontent.com/assets/26872587/24654155/1d14e2b4-18fe-11e7-8511-59dcccc2096e.png)

**This is the error hat I get**

![image](https://cloud.githubusercontent.com/assets/26872587/24654193/53d6d1f4-18fe-11e7-8289-896370ac9eb7.png)

**Comment by SourabhMakker** [comment] 2017-04-04 11:31
And,
from the list of dependent dlls are you have listed to add in the program I get the bellow error while adding them.

![image](https://cloud.githubusercontent.com/assets/26872587/24654659/499169dc-1900-11e7-814c-4f5179c09e30.png)

**Comment by SourabhMakker** [comment] 2017-04-04 12:34
The above issue is resolved by updating the VS to 2015 and installing MSMpiSetup. They are provided in the prerequisite folder.

Thank You for your help!

**Comment by zhouwangzw** [comment] 2017-04-04 12:45
@SourabhMakker VS2015 is required. But MSMpiSetup can be skipped if you just want to run Eval.

**Comment by zhouwangzw** [comment] 2017-04-04 12:46
I am closing the issue and please feel free to reopen it if needed.

**Closed by zhouwangzw** 2017-04-04 12:46 UTC

**Comment by SourabhMakker** [comment] 2017-04-14 10:30
Hi

As per the link https://github.com/Microsoft/CNTK/wiki/EvalDll-Evaluation-on-Windows#shipping-evaldll-library-with-your-windows-application

I am trying to add the dlls to my application but I get the error:
![image](https://cloud.githubusercontent.com/assets/26872587/25041121/624d3a72-212b-11e7-9543-e2f5c84a2aa9.png)


![image](https://cloud.githubusercontent.com/assets/26872587/25041141/8154c548-212b-11e7-9e4c-ed2923ccc23f.png)

**Comment by zhouwangzw** [comment] 2017-04-14 13:34
@SourabhMakker Your application needs to use X64 as the platform, instead of AnyCPU. For unittest, you should also use X64 in Test->Test Settings->Default Processor Architecture: X64.
Thanks,
