### ISSUE TITLE
Training AutoEncoder based TIMIT, different results with Microsoft wiki offered! 

### ISSUE THREAD

**Issue by Jaquier** [Microsoft/CNTK#848] opened 2016-09-18 00:44 UTC
Dear,  @frankseide  and @all
    I have trained Autoencoder based TIMIT sets, using HTK to get the log mel  filterbank as inputs. 
    All the configuration files used are downloaded from Microsoft wiki, they are stay the same, but I got the  last training results based  Linux  is : 
         **_Finished Epoch[25 of 25]: [Training] MeanSqErr.MSE = 155.27413646 \* 1124823; 
        totalSamplesSeen= 28120575; learningRatePerSample = 0.00039062501_;**
        epochTime=48.3299s
        CNTKCommandTrainEnd: TIMIT_TrainAutoEncoder
and the Microsoft wiki results is : 
          **_Finished Epoch[25 of 25]: [Training] MeanSqErr.MSE = 34.21343625 \* 1124823; 
          totalSamplesSeen = 28120575; learningRatePerSample = 0.00039062501;_** 
          epochTime=11.0518s
          CNTKCommandTrainEnd: TIMIT_TrainAutoEncoder

  I do not know the reason , and I want to know the reason !
 Hope your answers!

**Comment by arijit17** [comment] 2016-11-13 09:21
Hey, I know nothing about HTK. Can you teach me how to use HTK to prepare the input?

**Comment by mhuckvale** [comment] 2017-01-19 23:05
I have just tried TIMIT_TrainAutoEncoder_ndl_deprecated.cntk myself and got:

Finished Epoch[25 of 25]: [Training] MeanSqErr.MSE = 32.44323062 * 1124823; 
totalSamplesSeen = 28120575; learningRatePerSample = 0.00039062501; 
epochTime=54.9678s

Maybe the problem is in the generation of the feature files. My HCopyTimit.config file contained:
```
SOURCEKIND     = WAVEFORM
SOURCEFORMAT   = NIST
SAVECOMPRESSED = FALSE
SAVEWITHCRC    = FALSE
TARGETKIND     = FBANK_Z_D_A
TARGETRATE     = 100000
SOURCERATE     = 625
WINDOWSIZE     = 250000.0
PREEMCOEF      = 0.97
ZMEANSOURCE    = TRUE
USEHAMMING     = TRUE
NUMCHANS       = 24
ENORMALISE     = TRUE
ESCALE         = 1.0
LOFREQ         = 64
HIFREQ         = 8000
```

The HTK command was
HCopy -C HCopyTimit.config -S HCopyTimit.scp

Hope this helps.

**Comment by cha-zhang** [comment] 2017-07-15 00:31
Hope this issue has been resolved. Closing it now since it's very old. Feel free to open a new one if the issue persists.

**Closed by cha-zhang** 2017-07-15 00:31 UTC
