### ISSUE TITLE
"Attempt to access invalid address" when calling del

### ISSUE THREAD

**Issue by tinyfx** [Microsoft/CNTK#2316] opened 2017-09-07 20:00 UTC
I have a python class which creates a model and trains it. The model is a class variable but the learner, trainer and training session are not. The minibatch source is subclassed from UserMinibatchSource.

I use this class for grid searching hyper-parameters across 4 GPUs, with each instance (now) running in a separate process on a separate GPU. Initially, I used a pool from the Multiprocessing library and found that GPU memory usage slowly crept up. I tried using del and gc.collect() to clean up memory usage when I had finished training but to no avail. I was never able to reclaim all the allocated memory. Then I moved onto running each object in a separate process. This has apparently fixed/masked the memory leak, but now my screen freezes after a period of time.

The only useful debug information I can find is by calling cntk_py.set_gpumemory_allocation_trace_level(1) and then calling del on my object. Much freeing occurs, apparently successfully, but several fail, for example:

Freed buffer<float> DeviceData = 0000000B06C74C00 on DeviceId = 3; GPU Memory Free = 5989 MB of 8192 MB

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::Stop
    - Microsoft::MSR::CNTK::BaseMatrix<float>::GetNumElements
    - Microsoft::MSR::CNTK::BaseMatrix<float>::ZeroInit
    - Microsoft::MSR::CNTK::BaseMatrix<int>::ZeroValues
    - Microsoft::MSR::CNTK::GPUMatrix<float>::~GPUMatrix<float>
    - Microsoft::MSR::CNTK::GPUMatrix<double>::operator^=
    - Microsoft::MSR::CNTK::Matrix<short>::ReleaseMemory
    - Microsoft::MSR::CNTK::Matrix<float>::~Matrix<float>
    - Microsoft::MSR::CNTK::MatrixBase::operator=
    - Microsoft::MSR::CNTK::TensorView<float>::~TensorView<float>
    - CNTK::NDArrayView::~NDArrayView
    - CNTK::NDArrayView::SliceView
    - CNTK::NDArrayView::~NDArrayView
    - 00007FFCE6F0AF08 (SymFromAddr() error: Attempt to access invalid address.)
    - CNTK::Value::Value
    - CNTK::Value::Value
    - 00007FFCE6ECF685 (SymFromAddr() error: Attempt to access invalid address.)
    - 00007FFCE6EBE7BB (SymFromAddr() error: Attempt to access invalid address.)

or......

Freed buffer<float> DeviceData = 0000000B05418200 on DeviceId = 3; GPU Memory Free = 6028 MB of 8192 MB

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::Stop
    - Microsoft::MSR::CNTK::BaseMatrix<float>::GetNumElements
    - Microsoft::MSR::CNTK::BaseMatrix<float>::ZeroInit
    - Microsoft::MSR::CNTK::BaseMatrix<int>::ZeroValues
    - Microsoft::MSR::CNTK::GPUMatrix<float>::~GPUMatrix<float>
    - Microsoft::MSR::CNTK::GPUMatrix<double>::operator^=
    - Microsoft::MSR::CNTK::Matrix<short>::ReleaseMemory
    - Microsoft::MSR::CNTK::Matrix<float>::~Matrix<float>
    - Microsoft::MSR::CNTK::MatrixBase::operator=
    - Microsoft::MSR::CNTK::TensorView<float>::~TensorView<float>
    - CNTK::NDArrayView::~NDArrayView
    - CNTK::NDArrayView::SliceView
    - CNTK::NDArrayView::~NDArrayView
    - 00007FFCE6F0AF08 (SymFromAddr() error: Attempt to access invalid address.)
    - CNTK::Variable::Variable
    - CNTK::XavierInitializer
    - CNTK::TrainingSession::~TrainingSession
    - CNTK::TrainingSession::~TrainingSession

Any ideas? 

Thanks

**Comment by n17s** [comment] 2017-09-08 05:23
It is possible for memory usage to slowly increase during the first pass through the data, but it should stabilize after that. You did not mention whether you actually get an out of memory error if you run long enough. Do you?

**Comment by tinyfx** [comment] 2017-09-08 05:36
If I run without letting the process exit and sequentially train a number of objects, a cuda memory exception will occur.

**Comment by KeDengMS** [comment] 2017-09-09 00:57
Which version of CNTK are you running with? Calling del needs to synchronize with GPU, or you might yank memory away while it's being used by cuda kernels. That would cause GPU AV and leads to cuda failure.
The "Attempt to access invalid address" may come from non-standard stack frame on CPU. I don't think it's related to your memory leak issue.

**Comment by tinyfx** [comment] 2017-09-09 08:31
This happens on both 2 and 2.1 versions of cntk with python 3.6. Currently I'm not calling del (beucase of concerns as you suggest), just exiting the process and letting it clean up itself. GPU memory usage does not seem to escalate, but pagefile usage does. When my screen freezes nothing is maxed out (CPU, GPU, gpu memory, cpu memory, pagefile etc). 

I notice that the newer versions of the NVIDIA driver seem quite unstable. I've tested 385.28, 385.41, 384.94 and they seem to make my screen freeze without running cntk! Most of my testing above was using 382.53, I'm now using 376.19 which seems comparable, perhaps slightly higher GPU utilisation. I have 4x GTX1070 by the way, so not ideal for this.

**Comment by KeDengMS** [comment] 2017-09-09 15:58
You can try set environment variable CUDA_LAUNCH_BLOCKING=1 to see if forcing each cuda launch to be synchronous helps memory cleaning up. It will slow down the execution though. Another thing to try is cuda-memcheck.

**Comment by tinyfx** [comment] 2017-09-10 21:24
Setting CUDA_LAUNCH_BLOCKING=1 seems to have resulted in some stability; I have passed the point where previously it would have reliably crashed by. (Execution time has been increased to the point of there being no benefit using multiple processes however.)  I note that pagefile usage has gone from ~20GB to ~36GB over the period. I allow each completed process to fully die before spawning a new one so am at a loss to know why.

What does all this this suggest?

I haven't tried cuda-memcheck yet, since it has taken the last 12 hours to get this far. What am I looking for?

Thanks for your help with this

**Comment by tinyfx** [comment] 2017-09-11 06:58
I take it all back - it froze about an hour after writing the above. I tried to run CUDA memcheck, but it fails almost instantly. I expect this is due to the OS timing out during the kernel launch. I think there is a registry setting somewhere that may allow the timeout to be increased, I will look.

**Comment by KeDengMS** [comment] 2017-09-11 22:12
You can find some good slides [here](http://on-demand.gputechconf.com/gtc/2014/presentations/S4158-cuda-streams-best-practices-common-pitfalls.pdf) explaining synchronization including CUDA_LAUNCH_BLOCKING=1. With this ENV, all CUDA operations are synchronous w.r.t. the host. That would eliminate the chances for cudaFree to yank memory used by GPU. I am not sure why pagefile usage increases with it. @FDecaYed do you have any suggestions for debugging this?

**Comment by FDecaYed** [comment] 2017-09-13 22:00
For screen freeze:
Seems the system is not very stable and not necessary related to cntk. It could be driver, but it could also be a lot of other things. I think those versions are window driver, right? I am not aware of stable issues of those. If you have a reproduce step on screen freeze without running cntk, I could help investigate.

I would recommend you start from stress test your system on latest driver, first all 4 cards together, and then one by one. You can also stress test by some efficient cntk example that will keep GPU utilization 100% all the time.

For multi-process:
I never tried it before and not familiar with those library. To my understanding, you won't see benefit running multiple process on one card since it is just time slice and not efficient. You will only see benefit when there are a lot of GPU idle, in which case you should look at optimize it to get higher utilization with single process.

**Comment by tinyfx** [comment] 2017-09-18 05:57
Thanks @FDecaYed 

My system will freeze just running Windows on the latest drivers, but seems stable on older drivers. Probably this is telling me something, but what I don't know. I will investigate and run an efficient cntk example as you suggest.

Regarding the multiprocessing library, I went this way because GPU utilisation is just over 50%. The bottleneck is I think the UserMinibatchSource slicing data from numpy arrays, but I had lots of CPU cores idle.

**Comment by cha-zhang** [comment] 2017-10-13 00:00
I'm closing this since it doesn't appear to be a CNTK issue. Please reopen if needed.

**Closed by cha-zhang** 2017-10-13 00:00 UTC
