### ISSUE TITLE
simple question about simple2d example

### ISSUE THREAD

**Issue by Eomtaesan** [Microsoft/CNTK#866] opened 2016-09-23 06:02 UTC
I saw image classification example. the label data input is only one(class number of input image).
I want to fix label input to array(not only one). I find that label input of simple2d is two(ex :1 0 or 0 1).
So I want to edit label of simple2d. Is it okay to change the label type from integer to double(or float)?
And can I input more than 2? (I can fix .cntk file)

I will make 1296:1296*3:1296.
And my input/output data range is not [-1 ,1] or [0, 1], So I want to change trainingCriterion and evalCriterion(Softmax and tanh is not fit for me) What kind of criterion can I use?

**Comment by cha-zhang** [comment] 2017-07-15 00:24
I'm closing this since it's very old. Label can be anything if you are using a regression network.

**Closed by cha-zhang** 2017-07-15 00:24 UTC
