### ISSUE TITLE
Error: 'unordered_map' does not name a type, when compiled with Kaldi enabled

### ISSUE THREAD

**Issue by WangcsShuai** [Microsoft/CNTK#948] opened 2016-10-26 12:30 UTC
When I complied with kaldi enabled, there will be such an error, but when I remove that option, everything goes correct. BTW, the kaldi alone can be compiled correctly, and the g++ version is 4.8.4.

Thanks.

**Comment by mahilleb-msft** [comment] 2016-10-27 09:45
Currently we only compile and test against a specific Kaldi version (hash c024e8aa from their repository), see for example our Dockerfile (https://github.com/Microsoft/CNTK/blob/master/Tools/docker/CNTK-CPUOnly-Image/Dockerfile). We could perhaps switch to a more recent version at some point, but it's not clear to me how to choose a stable Kaldi version.
In the meantime, could you try compiling with the old Kaldi version, or, if you have a fix for the current one, I can see if it doesn't break against the old version.

Best, Mark

**Comment by danpovey** [comment] 2016-10-30 04:02
I doubt it's about the Kaldi version, none of that code has changed for a long time.
But the original poster needs to paste much more complete error messages.

**Comment by hahatt** [comment] 2016-11-24 08:57
I think this is the same error as error #119

**Comment by wolfma61** [comment] 2017-07-12 12:16
Since #119 seems to be fixed I close this one.
If this still occurs with the most recent released version, please reopen (or create a new issue) with sufficient information to reproduce the problem

**Closed by wolfma61** 2017-07-12 12:16 UTC
