### ISSUE TITLE
Significant delay in writing scalar summary to TensorBoard file

### ISSUE THREAD

**Issue by ghost** [Microsoft/CNTK#2035] opened 2017-06-24 14:12 UTC
My CNTK build summary is shown below 
```

Build info: 

		Built time: Jun 11 2017 03:27:41
		Last modified date: Fri Jun  9 10:55:23 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: yes
		With ASGD: yes
		Math lib: mkl
		CUDA_PATH: /misc/opt/cuda/8.0
		CUB_PATH: /home/uujjwal/cntk/cub-1.4.1
		CUDNN_PATH: /misc/opt/cudnn/5.1-cuda-8.0
		Build Branch: master
		Build SHA1: 274924836b6aea688f0a5225334862168c40acea (modified)
		Built by Source/CNTK/buildinfo.h$$0 on nefgpu10
		Build Path: /home/uujjwal/cntk/CNTK
		MPI distribution: Open MPI
		MPI version: 1.10.3

```

I am running a training code for training a 6-layer CNN architecture over ImageNet dataset with 1000 classes. The code is running fine, but I cannot see any scalar summary information in TensorBoard.

I can just see the graph structure. When I ran the same code yesterday (and later aborted to do parameter changes), I saw the scalar summary only after more than 5000 minibatch processing. This is surprising because,  my TensorBoardProgressWriter has been instantiated as follows -

`    tensorboard_writer = progress_print.TensorBoardProgressWriter(freq=100, rank=0, log_dir=tensorboard_logdir, model=network['output'])
`
I suppose that this should make the summary output written to the file after processing of 100 minibatches. But it does not happen.

I want to know that is this a bug or is this a normal behavior due to some other reason ? How can this be addressed ?

**Comment by duli2012** [comment] 2017-07-20 17:56
Hi, Ujjwal, could you please share your code with us so that we can reproduce the error?
Thanks.

**Comment by duli2012** [comment] 2017-08-15 18:08
Since no reply for more than three weeks, we close this issue now. We can reopen it later if needed.

**Closed by duli2012** 2017-08-15 18:08 UTC
