### ISSUE TITLE
Regression training using RAM from DDR rather no GPU

### ISSUE THREAD

**Issue by 256zib** [Microsoft/CNTK#981] opened 2016-11-01 08:46 UTC
[RegrPointsH1outTest_cntk.txt](https://github.com/Microsoft/CNTK/files/563642/RegrPointsH1outTest_cntk.txt)

Hi!

I'm training the regression model as showed in the file RegressionSimple.cntk. But when the cntk start minibatch loop, it use DDR RAM. Why it not using RAM from GPU?

![ddr](https://cloud.githubusercontent.com/assets/17701502/19884048/d00cd1aa-a028-11e6-8a3f-203b4f208cfc.png)

![screenshot](https://cloud.githubusercontent.com/assets/17701502/19884049/d00cf61c-a028-11e6-98d3-29d58ef9b21a.png)
Thank )

**Comment by awscodu** [comment] 2016-11-01 15:38
Did you download the binary for the GPU or the binaries for the CPU?
Double check because that might be your problem

**Comment by 256zib** [comment] 2016-11-01 15:52
I was build cntk on my computer for the GPU. if I run the convolution network, the data is loaded into the GPU. But also increases DDR. The letter I attached screenshot start convolution model
![convolution](https://cloud.githubusercontent.com/assets/17701502/19896134/4875a24e-a064-11e6-9768-94cbb3f79dd1.png)

**Comment by 256zib** [comment] 2016-11-01 15:53
I'll try to update to the latest version CNTK

**Comment by 256zib** [comment] 2016-11-01 15:57
I noticed that in the training increased memory for the GPU and DDR. In screenshot above line  "GPU Load" not always used, why GPU used not on 100%?

**Comment by awscodu** [comment] 2016-11-01 19:31
"When the network is small, the cost of transfering data to/from the GPU overshadows the benefit
of faster execution."- another post

If you have the latest drivers this may answer your question. However, I also know that cntk by default does not use 100% of your gpu to prevent heating issues from occurring during long session of training.

**Comment by wolfma61** [comment] 2017-07-12 12:00
I think what was said above is still accurate. Closing this issue ...
 Please reopen (or create a new issue) with sufficient information to reproduce the issue

**Closed by wolfma61** 2017-07-12 12:00 UTC
