### ISSUE TITLE
CNTK C# Managed API: CreateSequence<T>(inputVar.Shape, batch, false, device) throw exception

### ISSUE THREAD

**Issue by ebaas** [Microsoft/CNTK#1867] opened 2017-05-11 19:04 UTC
My LSTM model takes a time series as input which is broken into multiple sequences as below:

```
1|features -0.138918023895589 -0.14814345824795 -0.175130838931495 -0.125559008738214 -0.0567980844184435 -0.0575351815381229 -0.086603463819821 -0.0434121839267556 -0.0287496759806753 -0.0225752040277296 -0.00021578952281498 -0.0881665269853853 0.0115020339752281 0.0269085502616058 0 |# 6.89018891224382
1|features -0.0914017211661271 -0.118389101849672 -0.0688172716563908 -5.63473366206324E-05 -0.00079344445630003 -0.0298617267379981 0.0133295531550672 0.0279920611011475 0.0341665330540932 0.0565259475590079 -0.0314247899035625 0.0682437710570509 0.0836502873434286 0.0567417370818228 0 |# 6.833447175162
....
```

I am using the CreateSequence method to create values to inputVar

```
bool startFlag = true;
foreach (string features in featureList)
{
        var inputDataMap = new Dictionary<Variable, Value>();
        var outputDataMap = new Dictionary<Variable, Value>();
        IList<Variable> inputVars = modelFunc.Arguments;
        foreach (Variable inputVar in inputVars)
        {
               if (inputVar.Name == "features")
               {
                      batch = CreateFeatureBatch(features);
                     inputDataMap.Add(inputVar, Value.CreateSequence<float>(inputVar.Shape, batch, startFlag, device));
                }
       }

       IList<Variable> outputVars = modelFunc.Outputs;
       foreach (Variable outputVar in outputVars)
       {
                if (outputVar.Shape.Name == "z")
                {
                      outputDataMap.Add(outputVar, null);
                 }
        }
        modelFunc.Evaluate(inputDataMap, outputDataMap, device);
        var sequence = GetForecastSequence(outputDataMap, labelDimension);
        sequenceList.Add(sequence);

        startFlag = false; // for the subsequent sequences
}

```
It throws an exception at:

var outputData = outputVal.GetDenseData<float>(outputVar);

with message "Currently, only sequence starting with SequenceBegin is supported." when the startFlag is false.

Did I do it wrong? Any suggestions are very much appreciated!

**Comment by ebaas** [comment] 2017-05-11 19:26
The output of the last sequence is the forecast of a time series, but the previous sequences are supposed to be used to warm up the model, I think.

**Comment by zhouwangzw** [comment] 2017-05-15 12:24
@ebaas It is correct to use CreateSequece to pass sequence data for evaluation. The error basically indicates that the output data stored in outputVal does not represent a new sequence (a new sequence should start with SequenceBegin is true). Is your model trained with BrainScript or Python? 

ps. The line `outputVar.Shape.Name == "z" ` seems not correct. Should it be `outputVar.Name == "z"` instead?

**Comment by ebaas** [comment] 2017-05-15 16:21
My model is trained with BrainScript..

Thanks for the correction in my code.

**Comment by ebaas** [comment] 2017-05-16 17:18
Hi Zhou,

I have found a solution to it.  At line:

`inputDataMap.Add(inputVar, Value.CreateSequence<float>(inputVar.Shape, batch, device));
`   

Instead of breaking into multiple sequences, a batch containing complete sequence is built. The output is correct now.

Thank you so much!

**Comment by zhouwangzw** [comment] 2017-05-17 09:44
@ebaas Great to know the issue is resolved. Yes, when startFlag is set to false, it means a continuation of a previous sequence, as decribed in [the API reference](https://github.com/Microsoft/CNTK/wiki/CNTK-Library-Managed-API). So you should set startFlag to true when you evalaute a new sequence. 

I am closing the issue and feel free to re-open it if needed.

**Closed by zhouwangzw** 2017-05-17 09:44 UTC

**Comment by ebaas** [comment] 2017-05-17 22:49
Thanks, Zhou. This CNTK C# API is really helpful.
