### ISSUE TITLE
16 channel/band .tif files leads to instant crash

### ISSUE THREAD

**Issue by JjenksArch** [Microsoft/CNTK#803] opened 2016-08-30 15:27 UTC
Hey guys,
as the title says once I start loading a model with .tif files it leads to an instant crash(iv seen similar when my training/test image path is incorrect), which takes place just as the startEpoch runs.

I get a windows loading bar pop up stating that CNTK.exe has stopped working.
Any advice on getting high band/channel images to work?

**Comment by cha-zhang** [comment] 2017-07-16 14:49
Not sure if it's caused by OpenCV. Since this issue is very old I'm closing it. Feel free to open a new issue if there are still problems.

**Closed by cha-zhang** 2017-07-16 14:49 UTC
