### ISSUE TITLE
python abruptly stops while training while using MinibatchSourceFromData.next_minibatch() with sequences

### ISSUE THREAD

**Issue by vidyatshetty** [Microsoft/CNTK#2933] opened 2018-02-06 17:35 UTC
Hi,

I am using cntk for speaker recognition. my scp and mlf file looks like this,
**scp file:
C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SA2.mfc=C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SA2.mfc[0,212]
C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SI1027.mfc=C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SI1027.mfc[0,306]**
...............
**MLF file:

#!MLF!#
"C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SA2.lab"
0 21300000 FCJF0 -17989.648438
.
"C:/Users/vidya/htk/Timit_ASR/TIMIT/TRAIN/DR1/FCJF0/SI1027.lab"
0 30700000 FCJF0 -27676.513672
.**

**The reader code looks like this:**
features_data = C.io.HTKFeatureDeserializer(StreamDefs(speech_features = StreamDef(shape = feature_dimension, scp = feature_file)))
label_data = C.io.HTKMLFDeserializer(mapping_label_file, C.io.StreamDefs(speech_label = C.io.StreamDef(shape = label_dimension, mlf = label_file)), True)
data_minibatch_source = MinibatchSource([features_data, label_data])
stream_data = {features: data_minibatch_source.streams.speech_features, labels: data_minibatch_source.streams.speech_label}
 
**The python stops abruptly when it reaches this line of the code:**
minibatch = data_minibatch_source.next_minibatch(1024, input_map = stream_data)

I am referring  the tutorials and I am able to create readers, model but when i try to train the model using next_minibatch the python abruptly stops. I quiet don't understand what is wrong.  I believe it has something to do with minibatchSource. 
Kindly help me out.
Thanks

**Comment by KeDengMS** [comment] 2018-02-07 17:53
Seems like a crash. Is it possible to attach a debugger and get the callstack?

**Comment by vidyatshetty** [comment] 2018-02-08 17:16
Hi @KeDengMS  Thank you for writing.

Even when I attach a debugger it crashes.

It seems working when I use the TIMIT database in the examples\speech folder(glob_0000.scp, glob_0000.mlf and state.list) but not able to do it using my own data but I can train the network using my own data in brainscript but it crashes when I use it in python. I don't know if my data file configuration is wrong. but, I did use HTK to get MFCC features and label file.
Do I need a different data file configuration for speaker recognition task? because I read the documentation and it explains with respect to speech recognition I am bit confused if cntk expects different .scp and .mlf file for speaker recognition problem? [Also, I am trying to work on text independent speaker recognition problem] Please correct me if I am wrong.

Thanks

**Comment by KeDengMS** [comment] 2018-02-08 19:08
Sounds like a bug in Python side if the same data worked in BrainScript. Please share a repro if possible.

**Comment by vidyatshetty** [comment] 2018-02-09 20:06
@KeDengMS  thanks for writing.

next_minibatch runs if I don't give any arguments inside.
**minibatch = data_minibatch_source.next_minibatch**

but it crashes when I give arguments like,
**minibatch = data_minibatch_source.next_minibatch(1024, input_map)**
or
**minibatch = data_minibatch_source.next_minibatch(1024)**

The cmd log look like this before crashing,

![github_cntk_issue](https://user-images.githubusercontent.com/13535872/36047442-beaceb56-0da1-11e8-93fe-3c58206a26a5.PNG)

If you feel it is an error in the data files I am attaching two .mfc files which I got from htk please view it using HCOPY if the data looks good?
Kindly help me out
[github.zip](https://github.com/Microsoft/CNTK/files/1712267/github.zip)


Thanks

**Comment by KeDengMS** [comment] 2018-02-10 00:52
Thanks for sharing the data files. Can you also attach the CNTK Python/BrainScript code that uses them?

**Comment by vidyatshetty** [comment] 2018-02-10 01:16
@KeDengMS  Thanks for the response,

The  below is the python file,
[python_file.txt](https://github.com/Microsoft/CNTK/files/1712868/python_file.txt)

The brainscript works fine
If you need brainscript as well please let me know.

Thank you

**Comment by KeDengMS** [comment] 2018-02-10 01:20
There are only SA1.mfc and SA2.mfc. The python code seems to require training.txt/TrainMlf.txt/TimitStateList.txt. Besides, even though BrainScript works, please share them so I could have side by side comparsion.

**Comment by vidyatshetty** [comment] 2018-02-10 01:53
Oh my bad! Can I share the repo to your mail id? can you please send me your mail id?

**Comment by KeDengMS** [comment] 2018-02-14 18:57
Is it possible to have a private GitHub project or use some cloud storage, in case that data being too big for mail?

**Comment by vidyatshetty** [comment] 2018-02-14 22:52
@KeDengMS  I just shared my repo on onedrive with you at KeDeng  at microsoft dot com.
let me know if you have access to it.
Thanks

**Comment by vidyatshetty** [comment] 2018-02-15 00:22
@KeDengMS  I just shared my repo with you. Please pull from branch "vidya"

Thanks

**Comment by KeDengMS** [comment] 2018-02-15 01:07
Thanks. I cannot run the BrainScript from the repo after some try. Now it shows:

minibatchframesourcemulti: reading 1 feature sets and 1 label sets......attempt: error opening file 'C:/GITHUB_CNTK/FCJF0/SX127.mfc': No such file or directory, retrying 2-th time out of 5...

This files does not seem to exist in the repo. 

Please make sure you can run both BrainScript and Python without data path issue first.

**Comment by vidyatshetty** [comment] 2018-02-15 02:54
@KeDengMS  please pull the latest change from branch "vidya.  Now the Brainscript works without data path issue.
python crashes as I mentioned earlier.
Thanks

**Comment by KeDengMS** [comment] 2018-02-15 07:47
OK the crash seems to be a bug in exception thrown from readers. It was not captured and shown in output before crash. Here's the exception text:

Offset '7898': frame range state 'MJEB1' is not found in the statelist

So the root cause seems to be in the state list file. After checking it I found that MJEB1 is the last entry with file end on the same line. Then i tried to add a new line after it, and seems the crash is gone.

**Comment by vidyatshetty** [comment] 2018-02-15 08:26
@KeDengMS  I cannot thank you enough. I was just trying to figure out the error all this while. you saved my time. Thank you.
Also, I have one more question not related to the above mentioned issue. If you could could give me any comments that would be really helpful for me.

Is there any way I can refer this example https://msdn.microsoft.com/en-us/magazine/mt791798.aspx and approach the speaker recognition problem in this way?
where my mfcc features as a feature vector(extracted using matlab or other toolkit) and one hot vector as label and then read that data using CNTKTEXTFORMAT reader in brainscript and python (in python reading feature data as X and labels as Y numpy arrays) 
|features 1.52363911e+00 -2.13533559e+00 -8.55623967e-01 -4.65148844e-01 -1.24582325e+00...... |labels 0 0 0 1
|features 1.52363911e+00 -4.13533559e+00 -9.55623967e-01 -4.65148844e-01 -2.24582325e+00 ....|labels 0 0 1 0
......................................
............

Thank you

**Comment by KeDengMS** [comment] 2018-02-20 21:08
The example you mentioned uses BrainScript and you may want to rewrite it in Python. Since it is not related the resolved issue, I'm closing it now. If you have any problems in rewriting the example, please open a separate issue.

**Closed by KeDengMS** 2018-02-20 21:08 UTC
