### ISSUE TITLE
when CTC will be available?

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#1112] opened 2016-11-30 20:31 UTC
Hi

CTC should be released on 1.8 release, but this version never have been released!! Is there any plan to implement and release CTC? If yes, please let us know about it.

regards.

**Comment by cha-zhang** [comment] 2016-12-05 16:49
It's on our roadmap, but currently we don't have anyone working on it due to many other tasks. If anyone is willing to contribute, please help!

**Comment by mahilleb-msft** [comment] 2017-07-06 13:23
Seems a duplicate of #1491, which is resolved, please checkout there.

**Closed by mahilleb-msft** 2017-07-06 13:23 UTC
Labels: feature request
